### ISSUE TITLE
linux proxy support

### ISSUE THREAD

**Issue by jacobweinstock** [NetApp/ez-rancher#24]
@hulquest will have to fill in the details here.

add linux Proxy Support. cloudinit already supports this. 

linux system wide proxy seems to be a problem in cloudinit
https://bugs.launchpad.net/cloud-init/+bug/1089405

we'll probably need to do this in our first pass of cloudinit before rebooting, if its possible. Our first pass curls down a file and we'd need the proxy setup before that for it to work. maybe env vars with the curl command? stuff to look into.

this is the normal long term place for proxy settings: 
```bash
# /etc/environment:
http_proxy="http://username:password@proxysrv:8080/"
https_proxy="https://username:password@proxysrv:8080/"
ftp_proxy="ftp://username:password@proxysrv:8080/"
no_proxy=".mylan.local,.domain1.com,host1,host2"
```

cloudinit supports setting APT proxy settings
```yaml
# 1.6 (http_|ftp_|https_)proxy
  #
  # Proxies are the most common apt.conf option, so that for simplified use
  # there is a shortcut for those. Those get automatically translated into the
  # correct Acquire::*::Proxy statements.
  #
  # note: proxy actually being a short synonym to http_proxy
  proxy: http://[[user][:pass]@]host[:port]/
  http_proxy: http://[[user][:pass]@]host[:port]/
  ftp_proxy: ftp://[[user][:pass]@]host[:port]/
  https_proxy: https://[[user][:pass]@]host[:port]/
```
